os: osx
osx_image: xcode13.4
language: swift
script: xcodebuild clean build test -project /Users/carloskimura/Desktop/Projects/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO